correction functions with static values
EscobarMiranda/pernix-dashboard-frontend pull request #15
Opened 2016-10-27 20:43 UTC by LserranoPernix

2016-10-27 20:46 UTC, LserranoPernix commented
![url hard](https://cloud.githubusercontent.com/assets/20000917/19784647/c6f25be0-9c53-11e6-95ff-5db7621bb4de.png)
![secure](https://cloud.githubusercontent.com/assets/20000917/19784650/ca515ab6-9c53-11e6-8012-b4cb3a629dfb.png)
prevent entry into the app by force

2016-10-27 20:49 UTC, LserranoPernix commented
![admin](https://cloud.githubusercontent.com/assets/20000917/19784762/2f59bca0-9c54-11e6-8f2c-c56ad2cd82fb.PNG)
user admin
![user](https://cloud.githubusercontent.com/assets/20000917/19784765/30afd904-9c54-11e6-86cc-c298887b9560.PNG)
regular user
management of user permissions

2016-10-27 21:01 UTC, johnnyxu-pernix requested changes

2016-10-27 21:01 UTC, johnnyxu-pernix commented on app/components/admin/project/admin-project.controller.js
> +      }
Move this to the `app.run` so every time the app loads a new page it will validate if the session is active.

2016-10-27 21:02 UTC, johnnyxu-pernix commented
@LserranoPernix is by a Google account the only way to log in into the app?

2016-10-27 22:45 UTC, LserranoPernix commented
correct, only domain @Pernix-solutions will have access

2016-10-27 22:46 UTC, johnnyxu-pernix requested changes

2016-10-27 22:46 UTC, johnnyxu-pernix commented on app/components/login/login.controller.js
>      }
Remove this, unused activate.

2016-10-28 15:03 UTC, johnnyxu-pernix commented on app/components/service/user/user.service.js
> +    function islogged() {
**Suggestion:** Change the function name, this does not determine if the user is logged or not. Maybe you could change it to `verifyCredentials();`

2016-10-28 15:57 UTC, johnnyxu-pernix approved these changes

2016-10-28 16:00 UTC, merged